// <auto-generated />
using System;
using CadastroVeiculo.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroVeiculo.Migrations
{
    [DbContext(typeof(AberturaChamadoContext))]
    [Migration("20241220195921_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadastroVeiculo.Models.AberturaChamado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Colaboradorid")
                        .HasColumnType("int");

                    b.Property<string>("cepSolicitante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("dataAberturaChamado")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<string>("enderecoSolicitante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nomeSolicitante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("placaVeiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("Colaboradorid");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("CadastroVeiculo.Models.Colaborador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("enderecoSolicitante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nomeColaborador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("CadastroVeiculo.Models.AberturaChamado", b =>
                {
                    b.HasOne("CadastroVeiculo.Models.Colaborador", null)
                        .WithMany("AberturaChamado")
                        .HasForeignKey("Colaboradorid");
                });

            modelBuilder.Entity("CadastroVeiculo.Models.Colaborador", b =>
                {
                    b.Navigation("AberturaChamado");
                });
#pragma warning restore 612, 618
        }
    }
}
